{
 "title": "Airflow-Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "airflow_dag_last_status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_dag_last_status", "legendFormat": "{{dag_id}}-{{status}}" }
   ]
  },
  {
   "title": "airflow_dag_status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "airflow_dag_status", "legendFormat": "{{dag_id}}-{{status}}" }
   ]
  },
  {
   "title": "airflow_dag_run_duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "airflow_dag_run_duration", "legendFormat": "{{dag_id}}" }
   ]
  },
  {
   "title": "airflow_task_status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_task_status", "legendFormat": "{{dag_id}}" }
   ]
  }
 ]
}